pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              namespace: jenkins
            spec:
              containers:
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                command: ['sleep']
                args: ['infinity']
                volumeMounts:
                  - name: registry-credentials
                    mountPath: /kaniko/.docker
              volumes:
                - name: registry-credentials
                  secret:
                    secretName: regcred
                    items: 
                    - key: .dockerconfigjson
                      path: config.json
            '''
        }
    }
    
    environment {
        GIT_REPO_URL = 'https://github.com/wh123rus/Minions_dev.git'
        GIT_REPO_OPS_URL = 'https://github.com/1soooh/djangobuild.git'
        GIT_USER_NAME = 'wh123rus'
        GIT_USER_EMAIL = 'wh123rus@naver.com'
        DOCKER_IMAGE_NAME = '/my-django'
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    checkout([
                        $class: 'GitSCM', 
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[credentialsId: 'github', url: "${GIT_REPO_URL}"]],
                    ])
                    sh "pwd"
                    sh "ls -la"
                }
            }
        }

        stage('Build and Tag Docker Image') {
            steps {
                container('kaniko') {
                    script {
                        sh "executor --dockerfile=Dockerfile \
                        --context=dir://${env.WORKSPACE} \
                        --destination=${GIT_USER_NAME}${DOCKER_IMAGE_NAME}:v${env.BUILD_NUMBER} \
                        --destination=${GIT_USER_NAME}${DOCKER_IMAGE_NAME}:latest"
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                git branch: 'main', url: "${GIT_REPO_OPS_URL}"

                sh "sed -i 's|image:.*|image: ${GIT_USER_NAME}${DOCKER_IMAGE_NAME}:v${env.BUILD_NUMBER}|g' k8s/deployment.yaml"

                sh 'git add k8s/deployment.yaml'
                sh "git config --global user.email ${GIT_USER_EMAIL}"
                sh "git config --global user.name ${GIT_USER_NAME}"
                sh "git commit -m 'Jenkins Build Number - ${BUILD_NUMBER}'"

                withCredentials([gitUsernamePassword(credentialsId: 'github')]) {
                    sh 'git push origin main'
                }
            }            
        }
    }
}
